# Generated by Django 4.1.8 on 2023-04-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
