# Generated by Django 4.1.9 on 2023-06-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("contacto", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contacto",
            name="apellido",
        ),
        migrations.RemoveField(
            model_name="contacto",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="contacto",
            name="id",
        ),
        migrations.RemoveField(
            model_name="contacto",
            name="telefono",
        ),
        migrations.AddField(
            model_name="contacto",
            name="page_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="wagtailcore.page",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contacto",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contacto",
            name="mensaje",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contacto",
            name="nombre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
