# Generated by Django 4.1.8 on 2023-05-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StreamerPage',
            new_name='FutbolistasPage',
        ),
    ]
