# Generated by Django 4.1.8 on 2023-05-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('inicio', '0002_rename_streamerpage_futbolistaspage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FutbolistasPage',
            new_name='StreamerPage',
        ),
    ]
