# Generated by Django 4.1.8 on 2023-05-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('inicio', '0003_rename_futbolistaspage_streamerpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('Nombre', models.CharField(max_length=255)),
                ('Fundacion', models.DateField()),
                ('Estadio', models.CharField(max_length=255)),
                ('Escudo', models.CharField(max_length=255)),
                ('Entrenador', models.CharField(max_length=255)),
                ('Descripcion', models.TextField()),
                ('Redes_Sociales', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='StreamerPage',
        ),
    ]
