# Generated by Django 4.1.8 on 2023-05-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('inicio', '0004_equipopage_delete_streamerpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipoPage',
            new_name='StreamerPage',
        ),
    ]
