# Generated by Django 4.1.8 on 2023-05-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_rename_equipopage_streamerpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamerpage',
            old_name='Descripcion',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='streamerpage',
            old_name='Entrenador',
            new_name='birth_city',
        ),
        migrations.RenameField(
            model_name='streamerpage',
            old_name='Escudo',
            new_name='birth_coordinates',
        ),
        migrations.RenameField(
            model_name='streamerpage',
            old_name='Estadio',
            new_name='birth_country',
        ),
        migrations.RenameField(
            model_name='streamerpage',
            old_name='Fundacion',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='streamerpage',
            old_name='Nombre',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='streamerpage',
            old_name='Redes_Sociales',
            new_name='social_links',
        ),
    ]
