# Generated by Django 4.2.2 on 2023-06-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="intro",
        ),
        migrations.AddField(
            model_name="blogpage",
            name="enlace_redes_sociales",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpage",
            name="lugar_de_nacimiento",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpage",
            name="otros_detalles",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="date",
            field=models.DateField(verbose_name="Fecha de nacimiento"),
        ),
    ]
