# Generated by Django 4.2.2 on 2023-06-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpage_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=models.CharField(max_length=1000),
        ),
    ]
