# Generated by Django 4.1.8 on 2023-06-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_videogamepage_remove_blogpagegalleryimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogamepage',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='video_game_images'),
        ),
    ]
