# Generated by Django 4.1.8 on 2023-06-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_videogamepage_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogamepage',
            name='desarrollador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videogamepage',
            name='editor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videogamepage',
            name='genero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videogamepage',
            name='jugadores',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videogamepage',
            name='modosdejuego',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videogamepage',
            name='requisitos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
