# Generated by Django 4.1.8 on 2023-06-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('blog', '0008_videogamepage_desarrollador_videogamepage_editor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogamepage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
