# Generated by Django 4.1.8 on 2023-06-12 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('blog', '0009_alter_videogamepage_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogamepage',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='videogamepage',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
