# Generated by Django 4.1.9 on 2023-06-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acercade", "0002_alter_aboutpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="body",
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
