# Generated by Django 4.1.9 on 2023-06-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personajes",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "lugar_nacimiento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("videojuego", models.CharField(blank=True, max_length=255, null=True)),
                ("peso", models.CharField(blank=True, max_length=255, null=True)),
                ("altura", models.CharField(blank=True, max_length=255, null=True)),
                ("hijos", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "foto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
